name: helium-pktfwd
base: core20
adopt-info: pktfwd
summary: Lora network packet forwarder
description: |
  The packet forwarder is a program running on the host of a Lora gateway
  that forwards RF packets receive by the concentrator to a server through
  a IP/UDP link, and emits RF packets that are sent by the server.
  It can also emit a network-wide GPS-synchronous beacon signal used for
  coordinating all nodes of the network.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
    run-on: arm64

apps:
  pktfwd:
    command: bin/start.sh
    daemon: simple
    restart-condition: always
    plugs:
      - gpio
      - network
      - network-control
      - network-bind
      - serial-port
      - spi

parts:
  loragw:
    source: https://github.com/Lora-net/lora_gateway.git
    plugin: make
    override-pull: |
      snapcraftctl pull
      # get RAK overlays for the 2245
      git clone https://github.com/RAKWireless/rak_common_for_gateway.git
      # copy patched bits in place
      cp rak_common_for_gateway/lora/rak2245/library.cfg libloragw/library.cfg
      cp rak_common_for_gateway/lora/rak2245/loragw_spi.native.c libloragw/src/loragw_spi.native.c
      # copy configs so they get staged
      mkdir -p configs
      cp rak_common_for_gateway/lora/rak2245/global_conf/*.json configs/
      # copy patched forwarder
      mkdir -p pktfwd-override
      cp rak_common_for_gateway/lora/rak2245/lora_pkt_fwd.c pktfwd-override/
      # clean up
      rm -rf rak_common_for_gateway
    override-build: |
      make all
      cp -av * $SNAPCRAFT_PART_INSTALL/
    override-prime: |
      echo "not priming loragw build fragments"
  pktfwd:
    source: https://github.com/Lora-net/packet_forwarder.git
    plugin: make
    after: [ loragw ]
    build-environment:
      - LGW_PATH: "$SNAPCRAFT_STAGE/libloragw"
    override-build: |
      cp -av $SNAPCRAFT_STAGE/pktfwd-override/lora_pkt_fwd.c lora_pkt_fwd/src/
      make all
      # install
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av lora_pkt_fwd/lora_pkt_fwd $SNAPCRAFT_PART_INSTALL/bin/
      cp -av lora_pkt_fwd/*.sh $SNAPCRAFT_PART_INSTALL/bin/
      # copy configs
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      cp -av $SNAPCRAFT_STAGE/configs/*.json $SNAPCRAFT_PART_INSTALL/etc/
      sed -i 's/"autoquit_threshold":.*$/"autoquit_threshold": 0/' $SNAPCRAFT_STAGE/configs/*.json
      # set version
      VER="$(cat VERSION)"
      echo "setting version to: $VER"
      snapcraftctl set-version "$VER"
  helper:
    source: .
    plugin: dump
    organize:
      start.sh: bin/start.sh
