#! /bin/sh

# only start the daemon if all other interfaces are connected too
for interface in serial-port spi network-control; do
  if ! snapctl is-connected $interface; then
    exit 0
  fi
done

if snapctl services ${SNAP_NAME}.pktfwd | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.pktfwd 2>&1 || true
fi
